/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.MatHang;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author VanPhu
 */
public class frm_panel_MatHang extends javax.swing.JPanel {

    /**
     * Creates new form frm_panel_MatHang
     */
    public frm_panel_MatHang() {
        initComponents();
        btnAdd.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\add_mh.png", 50, 50));
        btnUpdate.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\update_mh.png", 50, 50));
        btnDelete.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\delete.png", 50, 50));
        btnAddG.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\addG.png", 50, 50));
        btnAddL.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnAddL.png", 50, 50));
        btnCloseTab.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnCloseTab.png", 50, 50));
        btnCloseAll.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnCloseAll.png", 50, 50));
        btnReset.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnReset.png", 50, 50));
        btnSearch.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\search.png", 30, 30));
    }

    public frm_panel_MatHang(JFrame main) {
        initComponents();
        btnAdd.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\add_mh.png", 50, 50));
        btnUpdate.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\update_mh.png", 50, 50));
        btnDelete.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\delete.png", 50, 50));
        btnAddG.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\addG.png", 50, 50));
        btnAddL.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnAddL.png", 50, 50));
        btnCloseTab.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnCloseTab.png", 50, 50));
        btnCloseAll.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnCloseAll.png", 50, 50));
        btnReset.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\btnReset.png", 50, 50));
        btnSearch.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\search.png", 30, 30));
        frm_panel_DanhSachMatHang dsmh = new frm_panel_DanhSachMatHang();
        tab.addTab("Danh sách mặt hàng", null, dsmh, "Danh sách mặt hàng!");
    }

    private ImageIcon getIScaleImage(String url, int w, int h) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scale = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon scalIcon = new ImageIcon(scale);
        return scalIcon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAddG = new javax.swing.JButton();
        btnAddL = new javax.swing.JButton();
        btnCloseTab = new javax.swing.JButton();
        btnCloseAll = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSuggestion1 = new BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion();
        comboBoxSuggestion2 = new BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSuggestion3 = new BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxSuggestion4 = new BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new BHX_Swings.bhx.swing.button.ButtonCustom();
        textFieldSuggestion1 = new BHX_Swings.bhx.swing.textfield_suggestion.TextFieldSuggestion();

        jToolBar2.setBackground(new java.awt.Color(0, 136, 70));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(true);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("Tạo sản phẩm");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnAdd);

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdate.setText("Cập nhật sản phẩm");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnUpdate);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Xóa sản phẩm");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnDelete);

        btnAddG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddG.setText("Tạo nhóm loại");
        btnAddG.setFocusable(false);
        btnAddG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddG.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnAddG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnAddG);

        btnAddL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddL.setText("Tạo loại sản phẩm");
        btnAddL.setFocusable(false);
        btnAddL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddL.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnAddL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnAddL);

        btnCloseTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCloseTab.setText("Đóng Tab");
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnCloseTab);

        btnCloseAll.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCloseAll.setText("Đóng All Tab");
        btnCloseAll.setFocusable(false);
        btnCloseAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseAll.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnCloseAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnCloseAll);

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReset.setText("Reset bộ lọc");
        btnReset.setFocusable(false);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnReset);

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setForeground(new java.awt.Color(0, 153, 51));
        tab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Nhóm loại");

        comboBoxSuggestion1.setEditable(false);
        comboBoxSuggestion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "1", "1", "1", "1", " ", " " }));
        comboBoxSuggestion1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N

        comboBoxSuggestion2.setEditable(false);
        comboBoxSuggestion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "1", "1", "1", "1", " ", " " }));
        comboBoxSuggestion2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Loại");

        comboBoxSuggestion3.setEditable(false);
        comboBoxSuggestion3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "1", "1", "1", "1", " ", " " }));
        comboBoxSuggestion3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Đơn vị tính");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Giá thành");

        comboBoxSuggestion4.setEditable(false);
        comboBoxSuggestion4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "1", "1", "1", "1", " ", " " }));
        comboBoxSuggestion4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Tìm kiếm sản phẩm");

        btnSearch.setMargin(new java.awt.Insets(20, 20, 20, 20));

        textFieldSuggestion1.setRound(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 518, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxSuggestion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4)
                                .addComponent(comboBoxSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddG;
    private javax.swing.JButton btnAddL;
    private javax.swing.JButton btnCloseAll;
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private BHX_Swings.bhx.swing.button.ButtonCustom btnSearch;
    private javax.swing.JButton btnUpdate;
    private BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion comboBoxSuggestion1;
    private BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion comboBoxSuggestion2;
    private BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion comboBoxSuggestion3;
    private BHX_Swings.bhx.swing.combobox.ComboBoxSuggestion comboBoxSuggestion4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTabbedPane tab;
    private BHX_Swings.bhx.swing.textfield_suggestion.TextFieldSuggestion textFieldSuggestion1;
    // End of variables declaration//GEN-END:variables
}
