/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.NhapHang;

import BHX_UI.PhieuNhap.frm_panel_PhieuNhap;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author VanPhu
 */
public class frm_Main_NhapHang extends javax.swing.JFrame {

    private String IdNhanVien = "";
    private int countPhieuNhap = 1;

    /**
     * Creates new form frm_Main_NhapHang
     */
    public frm_Main_NhapHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnAdd.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\page_nh.png", 50, 50));
        btnAddProduct.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\add_nh.png", 50, 50));
        btnClear.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\clear.png", 50, 50));
        btnClose.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\close.png", 50, 50));
        btnBaoCao.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\report.png", 50, 50));
        btnSpHetHang.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\warning.png", 50, 50));
        btnInfo.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\information.png", 50, 50));
        btnLogout.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\logout_toolbar.png", 50, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnSpHetHang = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 136, 70));

        jToolBar1.setBackground(new java.awt.Color(0, 136, 70));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("Tạo phiếu nhập hàng");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnAddProduct.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddProduct.setText("Tạo mặt hàng mới");
        btnAddProduct.setFocusable(false);
        btnAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddProduct.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAddProduct);

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClose.setText("Đóng Tab");
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClose);

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("Xóa tất cả Tab");
        btnClear.setFocusable(false);
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClear);

        btnBaoCao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBaoCao.setText("Báo cáo");
        btnBaoCao.setFocusable(false);
        btnBaoCao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaoCao.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnBaoCao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBaoCao);

        btnSpHetHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSpHetHang.setText("Sản phẩm hết hàng");
        btnSpHetHang.setFocusable(false);
        btnSpHetHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSpHetHang.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnSpHetHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSpHetHang);

        btnInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInfo.setText("Thông tin nhân viên");
        btnInfo.setFocusable(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnInfo);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLogout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        tab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        frm_panel_PhieuNhap pn = new frm_panel_PhieuNhap(this);
        int index = (tab.getTabCount() + 1);
        if (index <= 10) {
            if (checkPhieuNhapMax3()) {
                tab.addTab("Phiếu Nhập " + countPhieuNhap + "  ", getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\page_nh.png", 20, 20), pn, "Khởi tạo phiếu nhập hàng !");
                countPhieuNhap++;
                return;
            }
            JOptionPane.showMessageDialog(this, "Bạn chỉ được phép làm việc với 3 Tab phiếu nhập !");
            return;
        }
        JOptionPane.showMessageDialog(this, "Bạn chỉ được phép tạo tối đa 10 Tab !");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tab.removeAll();
        countPhieuNhap = 1;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int index = tab.getSelectedIndex();
        if (index >= 0) {
            tab.removeTabAt(index);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Main_NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Main_NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Main_NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Main_NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Main_NhapHang().setVisible(true);
            }
        });
    }

    private boolean checkPhieuNhapMax3() {
        int count = 1;
        frm_panel_PhieuNhap pn = new frm_panel_PhieuNhap(this);
        for (int i = 0; i < tab.getTabCount(); i++) {
            try {
                frm_panel_PhieuNhap pN = (frm_panel_PhieuNhap) tab.getTabComponentAt(i);
                count++;
            } catch (Exception e) {
            }
        }
        if (count <= 3) {
            return true;
        }
        return false;
    }

    private ImageIcon getIScaleImage(String url, int w, int h) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scale = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon scalIcon = new ImageIcon(scale);
        return scalIcon;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSpHetHang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
