/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.Dashboard;

import BHX_DAO.UsersLoginDAO;
import BHX_MODEL.Database.model.Nhanvien;
import BHX_MODEL.Database.model.UsersLogin;
import BHX_MODEL.Swing.model.Model_Card;
import BHX_UI.Login.frm_Login;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author VanPhu
 */
public class frm_dashboard extends javax.swing.JFrame {

    public String ID = null;
    private String taiKhoan = "";

    /**
     * Creates new form frm_dashboard
     */
    public frm_dashboard() {
        initComponents();
        this.pack();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        imageLogo.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\logo\\bachhoaxanhlogo.png", imageLogo.getWidth(), imageLogo.getHeight()));
        card1.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\admin.png", 160, 160), "Admin - Quản lý", "Nhân Viên", ""));
        card2.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\sell.png", 160, 160), "Quản lý - Bán hàng", "Nhân Viên", ""));
        card3.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\import.png", 160, 160), "Quản lý - Nhập hàng", "Nhân Viên", ""));
        card4.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\login.png", 160, 160), "Đăng nhập - Login", "Nhân Viên", ""));
        card5.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\logout.png", 160, 160), "Đăng xuất - Logout", "Nhân Viên", ""));
        card6.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\info.png", 160, 160), "About - Information", "Thông tin Công Ty", ""));
        imageIDLogin.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\user.png", imageIDLogin.getWidth(), imageIDLogin.getHeight()));
        loadThongTinNhanVien();
    }

    public frm_dashboard(String taiKhoan) {
        this.taiKhoan = taiKhoan;
        initComponents();
        this.pack();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        imageLogo.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\logo\\bachhoaxanhlogo.png", imageLogo.getWidth(), imageLogo.getHeight()));
        card1.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\admin.png", 160, 160), "Admin - Quản lý", "Nhân Viên", ""));
        card2.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\sell.png", 160, 160), "Quản lý - Bán hàng", "Nhân Viên", ""));
        card3.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\import.png", 160, 160), "Quản lý - Nhập hàng", "Nhân Viên", ""));
        card4.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\login.png", 160, 160), "Đăng nhập - Login", "Nhân Viên", ""));
        card5.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\logout.png", 160, 160), "Đăng xuất - Logout", "Nhân Viên", ""));
        card6.setData(new Model_Card(getIScaleImage("src\\\\BHX_IMG\\\\folderImages\\\\images\\\\icons\\\\info.png", 160, 160), "About - Information", "Thông tin Công Ty", ""));
        imageIDLogin.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\user.png", imageIDLogin.getWidth(), imageIDLogin.getHeight()));
        loadThongTinNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private ImageIcon getIScaleImage(String url, int w, int h) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scale = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon scalIcon = new ImageIcon(scale);
        return scalIcon;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imageLogo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        imageIDLogin = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        card1 = new BHX_Swings.bhx.component.Card_dash();
        card2 = new BHX_Swings.bhx.component.Card_dash();
        card3 = new BHX_Swings.bhx.component.Card_dash();
        card4 = new BHX_Swings.bhx.component.Card_dash();
        card5 = new BHX_Swings.bhx.component.Card_dash();
        card6 = new BHX_Swings.bhx.component.Card_dash();

        setTitle("DashBoard");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CỬA HÀNG SIÊU THỊ BÁCH HÓA XANH");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("CÔNG TY CÔ PHẦN THƯƠNG MẠI BÁCH HÓA XANH ");

        txtCV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCV.setText("Chức vụ:");

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        imageLogo.setMaximumSize(new java.awt.Dimension(300, 437));
        imageLogo.setMinimumSize(new java.awt.Dimension(300, 437));
        imageLogo.setPreferredSize(new java.awt.Dimension(300, 437));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("THỰC HIỆN: AN VÀ PHÚ");

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtName.setText("Tên Nhân Viên:");

        imageIDLogin.setMaximumSize(new java.awt.Dimension(300, 437));
        imageIDLogin.setMinimumSize(new java.awt.Dimension(300, 437));
        imageIDLogin.setPreferredSize(new java.awt.Dimension(300, 437));

        txtID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtID.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imageIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(331, 331, 331))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCV)
                                    .addComponent(txtName)
                                    .addComponent(txtID))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(imageIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCV)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        card1.setColor1(new java.awt.Color(0, 153, 102));
        card1.setColor2(new java.awt.Color(0, 255, 51));
        card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card1MouseExited(evt);
            }
        });
        jPanel2.add(card1);

        card2.setColor1(new java.awt.Color(153, 0, 153));
        card2.setColor2(new java.awt.Color(255, 0, 255));
        card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card2MouseExited(evt);
            }
        });
        jPanel2.add(card2);

        card3.setColor1(new java.awt.Color(0, 102, 102));
        card3.setColor2(new java.awt.Color(0, 255, 204));
        card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card3MouseExited(evt);
            }
        });
        jPanel2.add(card3);

        card4.setColor1(new java.awt.Color(0, 0, 204));
        card4.setColor2(new java.awt.Color(102, 102, 255));
        card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card4MouseExited(evt);
            }
        });
        jPanel2.add(card4);

        card5.setColor1(new java.awt.Color(0, 153, 153));
        card5.setColor2(new java.awt.Color(102, 255, 255));
        card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card5MouseExited(evt);
            }
        });
        jPanel2.add(card5);

        card6.setColor1(new java.awt.Color(255, 51, 51));
        card6.setColor2(new java.awt.Color(255, 153, 153));
        card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card6MouseExited(evt);
            }
        });
        jPanel2.add(card6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_card1MouseClicked

    private void card1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card1MouseEntered
        // TODO add your handling code here:
        card1.setColor1(Color.black);
        card1.updateUI();
    }//GEN-LAST:event_card1MouseEntered

    private void card1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card1MouseExited
        // TODO add your handling code here:
        card1.setColor1(new java.awt.Color(0, 153, 102));
        card1.updateUI();
    }//GEN-LAST:event_card1MouseExited

    private void card2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card2MouseEntered
        // TODO add your handling code here:
        card2.setColor1(Color.black);
        card2.updateUI();
    }//GEN-LAST:event_card2MouseEntered

    private void card2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card2MouseExited
        // TODO add your handling code here:
        card2.setColor1(new java.awt.Color(153, 0, 153));
        card2.updateUI();
    }//GEN-LAST:event_card2MouseExited

    private void card3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card3MouseEntered
        // TODO add your handling code here:
        card3.setColor1(Color.black);
        card3.updateUI();
    }//GEN-LAST:event_card3MouseEntered

    private void card3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card3MouseExited
        // TODO add your handling code here:
        card3.setColor1(new java.awt.Color(0, 102, 102));
        card3.updateUI();
    }//GEN-LAST:event_card3MouseExited

    private void card4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card4MouseEntered
        // TODO add your handling code here:
        card4.setColor1(Color.black);
        card4.updateUI();
    }//GEN-LAST:event_card4MouseEntered

    private void card4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card4MouseExited
        // TODO add your handling code here:
        card4.setColor1(new java.awt.Color(0, 0, 204));
        card4.updateUI();
    }//GEN-LAST:event_card4MouseExited

    private void card5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card5MouseEntered
        // TODO add your handling code here:
        card5.setColor1(Color.black);
        card5.updateUI();
    }//GEN-LAST:event_card5MouseEntered

    private void card5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card5MouseExited
        // TODO add your handling code here:
        card5.setColor1(new java.awt.Color(0, 153, 153));
        card5.updateUI();
    }//GEN-LAST:event_card5MouseExited

    private void card6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card6MouseEntered
        // TODO add your handling code here:
        card6.setColor1(Color.black);
        card6.updateUI();
    }//GEN-LAST:event_card6MouseEntered

    private void card6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card6MouseExited
        // TODO add your handling code here:
        card6.setColor1(new java.awt.Color(255, 51, 51));
        card6.updateUI();
    }//GEN-LAST:event_card6MouseExited

    private void card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card4MouseClicked
        // TODO add your handling code here:
        // Tài khoản phải trống mới cho đăng nhập.
        if (!taiKhoan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn đã thực hiện đăng nhập thành công !");
            return;
        }
        try {
            frm_Login login = new frm_Login();
            this.setVisible(false);
            login.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_card4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_dashboard().setVisible(true);
            }
        });
    }

    private void setData(String ID) {
        this.ID = ID;
    }

    private String getData() {
        return this.ID;
    }

    private void loadThongTinNhanVien() {
        try {
            UsersLoginDAO user_login_to_NhanVien = new UsersLoginDAO();
            Nhanvien nv = user_login_to_NhanVien.getEmployeeInfoByAccount(taiKhoan);
            if (nv == null) {
                txtID.setText("");
                txtName.setText("");
                txtCV.setText("");
            } else {
                txtID.setText("ID: " + nv.getManv());
                txtName.setText("Tên Nhân Viên: " + nv.getTennv());
                txtCV.setText("Chức Vụ: " + nv.getChucvu());
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BHX_Swings.bhx.component.Card_dash card1;
    private BHX_Swings.bhx.component.Card_dash card2;
    private BHX_Swings.bhx.component.Card_dash card3;
    private BHX_Swings.bhx.component.Card_dash card4;
    private BHX_Swings.bhx.component.Card_dash card5;
    private BHX_Swings.bhx.component.Card_dash card6;
    private javax.swing.JLabel imageIDLogin;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtCV;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
