/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.Login;

import BHX_DAO.UsersLoginDAO;
import BHX_UI.Dashboard.frm_dashboard;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author VanPhu
 */
public class frm_Login extends javax.swing.JFrame {

    private ImageIcon[] images;
    private int currentImageIndex;

    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        // Khởi tạo các hình ảnh
        images = new ImageIcon[4];
        images[0] = getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\login-pass.png", image.getWidth(), image.getHeight());
        images[1] = getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\login-pass2.png", image.getWidth(), image.getHeight());
        images[2] = getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\login-pass3.png", image.getWidth(), image.getHeight());
        images[3] = getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\login-pass4.png", image.getWidth(), image.getHeight());

        // Đặt hình ảnh mặc định
        image.setIcon(images[0]);

        // Sử dụng javax.swing.Timer để thay đổi hình ảnh sau mỗi 2 giây
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Thay đổi hình ảnh
                currentImageIndex = (currentImageIndex + 1) % images.length;
                image.setIcon(images[currentImageIndex]);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMK = new BHX_Swings.bhx.swing.textfield.PasswordField();
        txtTK = new BHX_Swings.bhx.swing.textfield.TextField();
        image = new javax.swing.JLabel();
        btnDN = new BHX_Swings.bhx.swing.button.ButtonCustom();
        btnThoat = new BHX_Swings.bhx.swing.button.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("ĐĂNG NHẬP HỆ THỐNG");

        txtMK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMK.setLabelText("Mật Khẩu");
        txtMK.setShowAndHide(true);

        txtTK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTK.setLabelText("Tên Tài Khoản");

        btnDN.setText("Đăng Nhập");
        btnDN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(txtTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        if (txtTK.getText().isEmpty() || txtMK.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin Tài khoản và Mật khẩu !");
            return;
        }

        UsersLoginDAO logIN_DAO = new UsersLoginDAO();
        try {

            char[] passwordChars = txtMK.getPassword(); // Lấy mật khẩu dưới dạng mảng ký tự
            String password = new String(passwordChars);
            if (!logIN_DAO.authenticate(txtTK.getText(), password)) {
                JOptionPane.showMessageDialog(this, "Đăng nhập không thành công !");
                return;
            }
            // Nếu thành công.
            // Kiểm tra thông tin tài khoản này có đăng nhập lần đầu tiên hay không ?
            int IsLoginFirst = logIN_DAO.checkLoginInfo(txtTK.getText(), password);
            if (IsLoginFirst == -1) {
                JOptionPane.showMessageDialog(this, "Đăng nhập không thành công !");
                return;
            }
            if (IsLoginFirst == 1) {
                // Bắt User đổi mật khẩu.
                frm_updatePasswordAndResetIsLoginFirst update = new frm_updatePasswordAndResetIsLoginFirst(this, txtTK.getText());
                this.setVisible(false);
                update.setVisible(true);
            } else {
                // Nếu cập nhật thành cônh chuyển về form DASH.
                frm_dashboard dashboard = new frm_dashboard(txtTK.getText());
                this.setVisible(false);
                dashboard.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra trong quá trình đăng nhập - Vui lòng kiểm tra thông tin đăng nhập !");
            return;
        }
    }//GEN-LAST:event_btnDNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    private ImageIcon getIScaleImage(String url, int w, int h) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scale = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon scalIcon = new ImageIcon(scale);
        return scalIcon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BHX_Swings.bhx.swing.button.ButtonCustom btnDN;
    private BHX_Swings.bhx.swing.button.ButtonCustom btnThoat;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private BHX_Swings.bhx.swing.textfield.PasswordField txtMK;
    private BHX_Swings.bhx.swing.textfield.TextField txtTK;
    // End of variables declaration//GEN-END:variables
}
