/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.Admin;

import BHX_UI.NhanVien.frm_panel_NhanVien_Add;
import BHX_UI.NhanVien.frm_panel_NhanVien_DanhSachNV;
import javax.swing.JFrame;

/**
 *
 * @author VanPhu
 */
public class frm_panel_Admin_NhanVien extends javax.swing.JPanel {

    private JFrame main;

    /**
     * Creates new form frm_panel_Admin_NhanVien
     */
    public frm_panel_Admin_NhanVien() {
        initComponents();
        tab.addTab("Tạo Thông Tin Nhân Viên", null, new frm_panel_NhanVien_Add(), "Tạo Thông Tin Nhân Viên.");
        tab.addTab("Danh sách Nhân Viên", null, new frm_panel_NhanVien_DanhSachNV(), "Xem danh sách Nhân Viêng");
    }

    public frm_panel_Admin_NhanVien(JFrame main) {
        this.main = main;
        initComponents();
        tab.addTab("Tạo Thông Tin Nhân Viên", null, new frm_panel_NhanVien_Add(), "Tạo Thông Tin Nhân Viên.");
        tab.addTab("Danh sách Nhân Viên", null, new frm_panel_NhanVien_DanhSachNV(), "Xem danh sách Nhân Viêng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneWin111 = new BHX_Swings.bhx.swing.srcollbarPanel.ScrollPaneWin11();
        tab = new javax.swing.JTabbedPane();

        scrollPaneWin111.setBackground(new java.awt.Color(255, 255, 255));

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        scrollPaneWin111.setViewportView(tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BHX_Swings.bhx.swing.srcollbarPanel.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
