/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.Admin;

import BHX_UI.PhieuNhap.frm_panel_DanhSachPN;
import BHX_UI.PhieuNhap.frm_panel_PhieuNhap;
import javax.swing.JFrame;

/**
 *
 * @author VanPhu
 */
public class frm_panel_Admin_NhapHang extends javax.swing.JPanel {

    /**
     * Creates new form frm_panel_Admin_NhapHang
     */
    public frm_panel_Admin_NhapHang() {
        initComponents();
        tab.addTab("Tạo phiếu nhập hàng", null, new frm_panel_PhieuNhap(), "Tạo phiếu nhập hàng");
        tab.addTab("Danh sách phiếu nhập hàng", null, new frm_panel_DanhSachPN(), "Xem danh sách phiếu nhập hàng");
    }

    public frm_panel_Admin_NhapHang(JFrame main) {
        initComponents();
        tab.addTab("Tạo phiếu nhập hàng", null, new frm_panel_PhieuNhap(main), "Tạo phiếu nhập hàng");
        tab.addTab("Danh sách phiếu nhập hàng", null, new frm_panel_DanhSachPN(main), "Xem danh sách phiếu nhập hàng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setForeground(new java.awt.Color(0, 136, 70));
        tab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
