/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.BanHang;

import BHX_DAO.MatHangDAO;
import BHX_MODEL.Object.model.ChitiethoadonObj;
import java.math.BigDecimal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author VanPhu
 */
public class frm_CanKi extends javax.swing.JFrame {

    private JFrame main;
    private String tenMH;
    private ChitiethoadonObj cthdObj;

    /**
     * Creates new form frm_CanKi
     */
    public frm_CanKi() {
        initComponents();
        setResizable(false);
    }

    public frm_CanKi(JFrame main, String tenMH, ChitiethoadonObj cthdObj) {
        this.main = main;
        this.tenMH = tenMH;
        this.cthdObj = cthdObj;
        initComponents();
        setLocationRelativeTo(main);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public static boolean isBigDecimal(Object obj) {
        return obj instanceof BigDecimal;
    }

    public static BigDecimal convertToBigDecimal(String str) {
        try {
            return new BigDecimal(str);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    public static boolean isBigDecimal(String str) {
        try {
            BigDecimal big = new BigDecimal(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSoLuong = new BHX_Swings.bhx.swing.textfield_suggestion.TextFieldSuggestion();
        buttonCustom1 = new BHX_Swings.bhx.swing.button.ButtonCustom();
        buttonCustom3 = new BHX_Swings.bhx.swing.button.ButtonCustom();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sản Phẩm: Tên");

        txtSoLuong.setForeground(new java.awt.Color(255, 0, 0));
        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        buttonCustom1.setText("Cân Ký");
        buttonCustom1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustom1ActionPerformed(evt);
            }
        });

        buttonCustom3.setText("Cancel");
        buttonCustom3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonCustom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustom3ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sản Phẩm Cần Cân Ký");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 321, Short.MAX_VALUE)
                        .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustom3ActionPerformed
        // TODO add your handling code here:
        this.main.setEnabled(true);
        dispose();
    }//GEN-LAST:event_buttonCustom3ActionPerformed

    private void buttonCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustom1ActionPerformed
        // TODO add your handling code here:
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số kí đã cân !");
            return;
        }
        if (isBigDecimal(txtSoLuong.getText())) {
            MatHangDAO mhDAO = new MatHangDAO();
            BigDecimal sum = convertToBigDecimal(txtSoLuong.getText());

            try {
                // Còn hàng nhưng không đủ só lượng.
                // Kiểm tra số lượng sau khi đã thay đỏi có đủ để bán không?
                // Nếu mặt hàng còn hàng nhưng không đủ số lượng để bán đối với sản phẩm không cân ký.
                frm_Main_BanHang frm_Main = (frm_Main_BanHang) this.main;
                for (ChitiethoadonObj cthd : frm_Main.getDanhSachPhieuTamToTabActive()) {
                    if (cthd.getMaSp().equals(cthdObj.getMaSp())) {
                        BigDecimal sum_To_Row = cthd.getSoLuong().add(sum); // Cộng số lượng hiện tại với số lượng hiện có trong row chi tiết hóa đơn trong tab active.
                        // Còn hàng nhưng không đủ só lượng.
                        // Kiểm tra số lượng sau khi đã thay đỏi có đủ để bán không?
                        // Nếu mặt hàng còn hàng nhưng không đủ số lượng để bán đối với sản phẩm không cân ký.
                        double soLuongTonKho = mhDAO.selectTonKhoMatHang(cthd.getMaSp());
                        if (soLuongTonKho > 0) {
                            double soLuongObj = soLuongTonKho - sum_To_Row.doubleValue();
                            if (soLuongObj < 0) {
                                JOptionPane.showMessageDialog(this, "Mặt hàng " + cthd.getMaSp().trim() + " số lượng hiện không đủ để bán !" + "\nSố lượng hiện có trong kho: " + soLuongTonKho, "Cảnh báo !", JOptionPane.WARNING_MESSAGE, null);
                                return;
                            }
                        }
                        break;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống: Trong quá trình tìm sản phẩm đã tồn tại trong tab active - ERROR: Không thể tìm hoặc lỗi trong quá trình tìm !");
                return;
            }

            // Xử lý đối với sản phẩm thêm mới vào bảng chi tiết hóa đơn.
            double soLuongTonKho = mhDAO.selectTonKhoMatHang(cthdObj.getMaSp());
            if (soLuongTonKho > 0) {
                double soLuongObj = soLuongTonKho - sum.doubleValue();
                if (soLuongObj < 0) {
                    JOptionPane.showMessageDialog(this, "Mặt hàng " + cthdObj.getMaSp().trim() + " số lượng hiện không đủ để bán !" + "\nSố lượng hiện có trong kho: " + soLuongTonKho, "Cảnh báo !", JOptionPane.WARNING_MESSAGE, null);
                    return;
                }
            }
            // Set số lượng cân kí.
            cthdObj.setSoLuong(sum);
            this.main.setEnabled(true);
            dispose();
            return;
        }
        JOptionPane.showMessageDialog(this, "Đây không phải là số - Vui lòng nhập 1 số !");
    }//GEN-LAST:event_buttonCustom1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.main.setEnabled(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_CanKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_CanKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_CanKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_CanKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_CanKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BHX_Swings.bhx.swing.button.ButtonCustom buttonCustom1;
    private BHX_Swings.bhx.swing.button.ButtonCustom buttonCustom3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private BHX_Swings.bhx.swing.textfield_suggestion.TextFieldSuggestion txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
