/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BHX_UI.NhanVien;

import BHX_DAO.NhanVienDAO;
import BHX_MODEL.Database.model.Nhanvien;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author VanPhu
 */
public class frm_QuanLyNhanVien extends javax.swing.JFrame {

    private String ID_NV = "NV001";
    private JFrame main = null;

    /**
     * Creates new form frm_QuanLyNhanVien
     */
    public frm_QuanLyNhanVien(JFrame main, String ID) {
        this.main = main;
        this.ID_NV = ID;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(main);
        btnInfo.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\information.png", 50, 50));
        btnUpdate.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\report.png", 50, 50));
    }

    public frm_QuanLyNhanVien() {
        initComponents();
        btnInfo.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\information.png", 50, 50));
        btnUpdate.setIcon(getIScaleImage("src\\BHX_IMG\\folderImages\\images\\icons\\report.png", 50, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnInfo = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        frm_main_Scroll = new BHX_Swings.bhx.swing.srcollbarPanel.ScrollPaneWin11();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1587, 857));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 136, 70));

        jToolBar1.setBackground(new java.awt.Color(0, 136, 70));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInfo.setText("Thông tin nhân viên");
        btnInfo.setFocusable(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInfo);

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdate.setText("Cập Nhật Thông Tin");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUpdate);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        frm_main_Scroll.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frm_main_Scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frm_main_Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        //
        if (this.ID_NV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Load thông tin nhân viên không thành công !");
            return;
        }
        try {
            NhanVienDAO nvDAO = new NhanVienDAO();
            Nhanvien nv = nvDAO.selectWithID(ID_NV);
            frm_panel_NhanVien_Show frm_NV_Show = new frm_panel_NhanVien_Show();
            frm_NV_Show.loadInfo(ID_NV);
            frm_main_Scroll.setViewportView(frm_NV_Show);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Load thông tin nhân viên không thành công !" + e.toString());
            return;
        }
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (this.ID_NV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Load thông tin nhân viên không thành công !");
            return;
        }
        try {
            NhanVienDAO nvDAO = new NhanVienDAO();
            Nhanvien nv = nvDAO.selectWithID(ID_NV);
            frm_panel_NhanVien_Update frm_NV_Update = new frm_panel_NhanVien_Update(ID_NV);
            frm_NV_Update.loadInfo(ID_NV);
            frm_main_Scroll.setViewportView(frm_NV_Update);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Load thông tin nhân viên không thành công !" + e.toString());
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        // 
        if (this.main != null) {
            this.main.setEnabled(true);
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private ImageIcon getIScaleImage(String url, int w, int h) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scale = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon scalIcon = new ImageIcon(scale);
        return scalIcon;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnUpdate;
    private BHX_Swings.bhx.swing.srcollbarPanel.ScrollPaneWin11 frm_main_Scroll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
